In [4]:
import pandas as pd
alunos = {'Nome':['Ricardo', 'Kleber', 'Pedro', 'Carlos'],
         'Nota':[4, 7, 5.5, 9],
         'Aprovado':['Não', 'Sim', 'Não', 'Sim']}

In [5]:
dataframe = pd.DataFrame(alunos)

In [6]:
display(dataframe)

Nome  Nota Aprovado
0  Ricardo   4.0      Não
1   Kleber   7.0      Sim
2    Pedro   5.5      Não
3   Carlos   9.0      Sim

In [8]:
objetos1 = pd.Series([2, 6, 9, 14, 15, 8])
print(objetos1)

0     2
1     6
2     9
3    14
4    15
5     8
dtype: int64


In [9]:
import numpy as np
array = np.array([2, 6, 9, 14, 15, 8])
print(array)

[ 2  6  9 14 15  8]


In [11]:
import numpy as np
array = np.array([(2, 6, 9, 14, 15, 8), (2, 3, 7, 5, 7, 9)])
print(array)

[[ 2  6  9 14 15  8]
 [ 2  3  7  5  7  9]]
